### ISSUE TITLE
flycheck pull request?

### ISSUE THREAD

**Issue by robstewart57** [kisaragi-hiu/flycheck-textlint#1]
Would this be suitable for merging with flycheck upstream?

This has been asked:

https://github.com/flycheck/flycheck/issues/899#issuecomment-455617723

**Comment by kisaragi-hiu** [comment]
I hope; I've opened the PR at https://github.com/flycheck/flycheck/pull/1534.

**Comment by kisaragi-hiu** [comment]
Closing as the PR has been merged. Thank you!

**Comment by robstewart57** [comment]
@kisaragi-hiu This is brilliant! I'm delighted this is now built in to flycheck.

It's a good idea that you've turned this repository into a tutorial page.

Thank you.

**Comment by cdlm** [comment]
I'm trying to migrate my config to the new upstream support… however all I get now is:
```
  textlint
    - may enable:         Automatically disabled!
```
Executable and config files are found.

I was using `(flycheck-add-mode 'textlint 'tex-mode)`, which seemed to work, but doesn't anymore… was that wrong? Also I don't think I really understand the difference between setting `flycheck-textlint-plugin-alist` and adding stuff under "plugins" in `.textlintrc`.

Basically I'd like textlint in text, markdown, LaTeX, and HTML files with the available plugins, and the text plugin in files with `.pillar` extension (a markup language for which I can make do with partial support); here's what I have:
```elisp
  (use-package flycheck
    :config
    (setq flycheck-global-modes (remove 'yaml-mode flycheck-global-modes))
    (setq flycheck-textlint-config "~/.config/textlint/textlintrc.json")
    (add-to-list 'flycheck-textlint-plugin-alist '(tex-mode . "@textlint/latex"))
    (add-to-list 'flycheck-textlint-plugin-alist '(pillar-mode . "@textlint/text"))
    (add-to-list 'flycheck-textlint-plugin-alist '(html-mode . "@textlint/html")))
```
